apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
spec:
  containers:
  - name: redis
    image: gcr.io/khalifa-iti-project/redis-challenge-image
    ports:
    - containerPort: 80